from __future__ import annotations

from io import BytesIO
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    ListFlowable,
    ListItem,
)


def _pct(x: Any) -> str:
    try:
        return f"{float(x) * 100:.1f}%"
    except Exception:
        return "N/A"


def build_triage_pdf_bytes(
    triage_result: Dict[str, Any],
    patient_id: Optional[str] = None,
    study_id: Optional[str] = None,
    generated_by: str = "Stroke AI Triage System",
    gradcam_png_path: Optional[str] = None,
) -> bytes:
    """
    Returns PDF bytes (in-memory). Safe to return via FastAPI StreamingResponse.
    """

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
        title="Stroke AI Triage Report",
    )

    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="H1",
            parent=styles["Heading1"],
            fontSize=18,
            leading=22,
            spaceAfter=10,
        )
    )
    styles.add(
        ParagraphStyle(
            name="H2",
            parent=styles["Heading2"],
            fontSize=12,
            leading=14,
            spaceBefore=10,
            spaceAfter=6,
        )
    )
    styles.add(
        ParagraphStyle(
            name="Small",
            parent=styles["BodyText"],
            fontSize=9,
            leading=11,
            textColor=colors.HexColor("#334155"),
        )
    )

    story: List[Any] = []

    #Header
    story.append(Paragraph("Stroke AI Triage Report", styles["H1"]))
    meta_lines = []
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    meta_lines.append(f"<b>Generated:</b> {now}")
    meta_lines.append(f"<b>Generated by:</b> {generated_by}")
    if patient_id:
        meta_lines.append(f"<b>Patient ID:</b> {patient_id}")
    if study_id:
        meta_lines.append(f"<b>Study ID:</b> {study_id}")
    story.append(Paragraph("<br/>".join(meta_lines), styles["Small"]))
    story.append(Spacer(1, 12))

    #Summary table
    stroke_present = triage_result.get("stroke_present")
    stroke_type = triage_result.get("stroke_type", "N/A")
    severity = triage_result.get("severity", "N/A")
    review_priority = triage_result.get("review_priority", "N/A")

    summary_data = [
        ["Stroke detected", "Stroke type", "Severity", "Review priority"],
        [
            "YES" if stroke_present else "NO",
            str(stroke_type),
            str(severity).upper(),
            str(review_priority).replace("_", " ").upper(),
        ],
    ]

    t = Table(summary_data, colWidths=[
              1.5 * inch, 1.7 * inch, 1.2 * inch, 1.9 * inch])
    t.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, 0), 10),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#94a3b8")),
                ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#f1f5f9")),
                ("TEXTCOLOR", (0, 1), (-1, 1), colors.HexColor("#0f172a")),
                ("FONTSIZE", (0, 1), (-1, 1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(t)
    story.append(Spacer(1, 12))

    #Reasons
    reasons = triage_result.get("reasons", [])
    story.append(Paragraph("Clinical Reasons", styles["H2"]))
    if reasons:
        bullets = ListFlowable(
            [ListItem(Paragraph(str(r), styles["BodyText"])) for r in reasons],
            bulletType="bullet",
            start="circle",
            leftIndent=16,
        )
        story.append(bullets)
    else:
        story.append(Paragraph("No reasons returned.", styles["BodyText"]))
    story.append(Spacer(1, 10))

    #Hemorrhage probabilities
    hem = triage_result.get("hemorrhage", {})
    hem_probs = hem.get("subtypes", {}) if isinstance(hem, dict) else {}
    hem_meta = hem.get("meta", {}) if isinstance(hem, dict) else {}

    story.append(Paragraph("CT Hemorrhage Probabilities", styles["H2"]))
    story.append(
        Paragraph(
            f"CT slices analyzed: <b>{hem_meta.get('num_slices', 'N/A')}</b>",
            styles["BodyText"],
        )
    )
    if hem_probs:
        rows = [["Label", "Probability"]]
        for k, v in hem_probs.items():
            rows.append([str(k), _pct(v)])
        table = Table(rows, colWidths=[2.8 * inch, 1.3 * inch])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f172a")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#94a3b8")),
                    ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#ffffff")),
                    ("ALIGN", (1, 1), (1, -1), "RIGHT"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                ]
            )
        )
        story.append(Spacer(1, 6))
        story.append(table)
    else:
        story.append(
            Paragraph("No hemorrhage probabilities available.", styles["BodyText"]))
    story.append(Spacer(1, 10))

    #ISLES
    isc = triage_result.get("ischemia", {}) if isinstance(
        triage_result.get("ischemia"), dict) else {}
    story.append(Paragraph("MRI Ischemia Output", styles["H2"]))
    story.append(
        Paragraph(
            f"Lesion volume (ml): <b>{isc.get('lesion_volume_ml', 'N/A')}</b><br/>"
            f"Mask path: <font size='8'>{isc.get('mask_path', 'N/A')}</font>",
            styles["BodyText"],
        )
    )
    story.append(Spacer(1, 10))

    #Grad-CAM img
    if gradcam_png_path:
        p = Path(gradcam_png_path)
        if p.exists():
            story.append(
                Paragraph("CT Explainability (Grad-CAM)", styles["H2"]))
            img = Image(str(p))
            img._restrictSize(6.5 * inch, 3.6 * inch)
            story.append(img)
            story.append(Spacer(1, 8))
        else:
            story.append(
                Paragraph("Grad-CAM image requested but file was not found.", styles["Small"]))

    #Footer
    story.append(Spacer(1, 14))
    story.append(
        Paragraph(
            "Disclaimer: Research prototype. Requires clinical validation before real-world use.",
            styles["Small"],
        )
    )

    doc.build(story)
    pdf_bytes = buf.getvalue()
    buf.close()
    return pdf_bytes
